name: Main
on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        rubyopt: [""]
        include:
          - ruby: "3.3"
            rubyopt: "--enable-frozen-string-literal --debug-frozen-string-literal"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Generate lockfile
        run: bundle lock

      - name: Run tests
        run: bundle exec rake test RUBYOPT="${{ matrix.rubyopt }}"
